# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df6437cf9d94e7c4cf7f2f575c0c16b6b198e97f2426483adde30efa8629dc9050b089c844da47a2f5e9b81411d56f8cdbbeae19c74a383e20fab6cca4278da3

test:
  secret_key_base: c377183ae2ea87507356374fe3376afb067699423202052ce2f0c62390621d41f9708301e6098abaeccf8fc328a692b750f67f83ef08052cf5e8568006f9b81f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
